# /pipelines/azure-pipelines.yml
pool:
  vmImage: windows-2019
  steps:
  - task: PowerShell@2
    displayName: "Run Pester tests"
    inputs:
      targetType: "inline"
      script: |
        Set-Location ./Tests
        Invoke-Pester -CI
        ignoreLASTEXITCODE: true
  
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: "NUnit"
      testResultsFiles: "**/Test*.xml"
      failTaskOnFailedTests: true
      testRunTitle: "Runatcloud tests validation"
  